import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync } from 'node:fs';

const skillUrl = new URL('../skills/expressivecss/SKILL.md', import.meta.url);
const skillDirectory = new URL('../skills/expressivecss/', import.meta.url);
const componentsDirectory = new URL('./components/', skillDirectory);
const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const research = readFileSync(new URL('../docs/agents/expressivecss-skill-research.md', import.meta.url), 'utf8');
const changelog = readFileSync(new URL('../CHANGELOG.md', import.meta.url), 'utf8');
const m3Guidelines = readFileSync(new URL('../m3-guidelines.md', import.meta.url), 'utf8');
const skill = readFileSync(skillUrl, 'utf8');
const bodyStart = skill.indexOf('\n---\n', 4);
const frontmatter = skill.slice(4, bodyStart);
const body = skill.slice(bodyStart + 5);

const supportGuides = [
  'expressivecss-install/SKILL.md',
  'expressivecss-design/SKILL.md',
  'expressivecss-usage/SKILL.md',
  'expressivecss-theming/SKILL.md',
  'expressivecss-runtime/SKILL.md',
  'expressivecss-accessibility/SKILL.md',
];

const componentEntries = [...body.matchAll(/- \[([^\]]+)\]\(\.\/components\/([a-z-]+\.md)\)/g)]
  .map((match) => ({ label: match[1], name: match[2] }));
const componentLinks = componentEntries.map(({ name }) => name);
const componentFiles = readdirSync(componentsDirectory)
  .filter((name) => name.endsWith('.md'))
  .sort();
const retiredClasses = new Set([
  'btn',
  'modal',
  'nav-wrapper',
  'brand-logo',
  'card-content',
  'lever',
  'filled-in',
  'materialize-textarea',
  'input-field',
]);

describe('the ExpressiveCSS agent skill', () => {
  test('is a portable root skill with a concise discovery trigger', () => {
    assert.ok(skill.startsWith('---\n'));
    assert.ok(bodyStart > 4, 'frontmatter is not closed');
    assert.match(frontmatter, /^name: expressivecss$/m);
    assert.match(frontmatter, /^  author: BaezFJ$/m);
    assert.match(frontmatter, /^  version: "0\.4\.0"$/m);

    const description = frontmatter.match(/^description: (.+)$/m)?.[1];
    assert.ok(description, 'description is missing');
    assert.ok(description.length <= 60, `description is ${description.length} characters`);
    assert.ok(description.endsWith('.'), 'description is not a sentence');
    assert.match(description, /^Use ExpressiveCSS for accessible Material 3 interfaces\.$/);
    assert.doesNotMatch(skill, /\/home\/|[A-Z]:\\Users\\/, 'skill contains a machine-local path');
    assert.doesNotMatch(skill, /\]\(\.\.\//, 'root skill links outside the portable skill directory');
  });

  test('routes each task to a focused guide with valid frontmatter', () => {
    for (const path of supportGuides) {
      assert.ok(body.includes(`](${`./${path}`})`), `${path} is not linked from the root skill`);
      const url = new URL(path, skillDirectory);
      assert.ok(existsSync(url), `${path} does not exist`);
      const guide = readFileSync(url, 'utf8');
      assert.ok(guide.startsWith('---\n'), `${path} has no frontmatter`);
      assert.match(guide, new RegExp(`^name: ${path.split('/')[0]}$`, 'm'));
      const description = guide.match(/^description: (.+)$/m)?.[1];
      assert.ok(description, `${path} has no description`);
      assert.ok(description.length <= 60, `${path} description is too long`);
      assert.ok(description.endsWith('.'), `${path} description is not a sentence`);
      assert.doesNotMatch(guide, /\/home\/|[A-Z]:\\Users\\/, `${path} contains a machine-local path`);
      assert.doesNotMatch(guide, /\]\(\.\.\/\.\.\//, `${path} links outside the portable skill directory`);
    }
  });

  test('lists every generated component guide exactly once', () => {
    assert.equal(componentFiles.length, 46);
    assert.deepEqual([...componentLinks].sort(), componentFiles);
    assert.equal(new Set(componentLinks).size, componentLinks.length, 'a component guide is listed more than once');

    for (const name of componentFiles) {
      const guideUrl = new URL(name, componentsDirectory);
      const guide = readFileSync(guideUrl, 'utf8');
      assert.match(guide, /^<!-- Generated by scripts\/gen-expressivecss-skill\.mjs\. Do not edit\. -->/);
      const title = guide.match(/^### (.+)$/m)?.[1];
      assert.equal(title, componentEntries.find((entry) => entry.name === name)?.label);
      assert.match(guide, /\[Component documentation\]\(https:\/\/www\.expressivecss\.com\/.+\.html\.md\)/);
      const sourcePath = guide.match(
        /\[Repository source\]\(https:\/\/github\.com\/BaezFJ\/ExpressiveCSS\/blob\/master\/(docs\/src\/pages\/.+\.astro)\)/,
      )?.[1];
      assert.ok(sourcePath, `${name} has no portable repository source link`);
      assert.ok(existsSync(new URL(`../${sourcePath}`, import.meta.url)), `${name} source link is broken`);
      assert.match(guide, /#### Contract/);
      assert.match(guide, /#### Syntax\n\n```(?:html|js)/);
      assert.match(guide, /#### Rules/);
      const syntax = guide.match(/#### Syntax\n\n```(?:html|js)\n([\s\S]+?)\n```/)?.[1];
      assert.ok(syntax, `${name} has no complete syntax example`);
      const syntaxClasses = [...syntax.matchAll(/class=["']([^"']+)["']/g)]
        .flatMap((match) => match[1].split(/\s+/));
      assert.deepEqual(
        syntaxClasses.filter((className) => retiredClasses.has(className)),
        [],
        `${name} must not teach retired Materialize classes`,
      );
      assert.doesNotMatch(guide, /\]\(\.\.\/\.\.\//, `${name} links outside the portable skill directory`);
      assert.doesNotMatch(guide, /\]\(#[^)]+\)/, `${name} contains a fragment from its source document`);
      assert.doesNotMatch(guide, /\/home\/|[A-Z]:\\Users\\/, `${name} contains a machine-local path`);
    }
  });

  test('keeps generated contracts focused on the selected component', () => {
    const guide = (name) => readFileSync(new URL(name, componentsDirectory), 'utf8');
    assert.match(guide('snackbar.md'), /#### Syntax\n\n```js\nnew Expressive\.Snackbar/);
    assert.doesNotMatch(guide('buttons.md'), /The FAB's actions|aria-expanded/);
    assert.doesNotMatch(guide('date-picker.md'), /A <dialog> takes no name/);
    assert.doesNotMatch(guide('time-picker.md'), /A <dialog> takes no name/);
    assert.doesNotMatch(guide('chips.md'), /^\| Type \|/m);
    assert.doesNotMatch(guide('progress.md'), /\]\(#loading-indicator\)/);
  });

  test('keeps card actions out of navigation landmarks', () => {
    assert.doesNotMatch(m3Guidelines, /Actions \(`<nav>` of buttons/);
    assert.match(m3Guidelines, /Actions \(`<div class="actions">` of buttons/);
  });

  test('keeps generated component guides synchronized with their sources', () => {
    assert.equal(packageJson.scripts['build:skill'], 'node scripts/gen-expressivecss-skill.mjs');
    const result = spawnSync(process.execPath, ['scripts/gen-expressivecss-skill.mjs', '--check'], {
      cwd: new URL('..', import.meta.url),
      encoding: 'utf8',
    });
    assert.equal(result.status, 0, `${result.stdout}${result.stderr}`);
    assert.match(result.stdout, /46 ExpressiveCSS component guides are current\./);
  });

  test('assigns authority by question and version', () => {
    for (const url of [
      'https://www.expressivecss.com/m3-guidelines.md',
      'https://www.expressivecss.com/llm.md',
      'https://github.com/BaezFJ/ExpressiveCSS/blob/master/semantics.json',
      'https://www.expressivecss.com/SEMANTICS.md',
      'https://github.com/BaezFJ/ExpressiveCSS/blob/master/docs/agents/expressivecss-skill-research.md',
    ]) {
      assert.ok(skill.includes(`](${url})`), `${url} is not linked`);
    }

    assert.match(body, /## Authority by question/);
    assert.doesNotMatch(body, /Resolve decisions in this order/);
    assert.match(body, /\*\*Design intent:\*\*.*component choice.*adaptive behavior/);
    assert.match(body, /\*\*Shipped contract:\*\*.*elements.*classes.*options.*methods/);
    assert.match(body, /\*\*Authored semantics:\*\*.*semantics\.json/);
    assert.match(body, /\*\*Runtime truth:\*\*.*Sass.*TypeScript.*tests/);
    assert.match(body, /older.*installed version.*matching repository tag/is);
  });

  test('keeps the load-bearing design, usage, runtime, theme, and accessibility rules', () => {
    const install = readFileSync(new URL('expressivecss-install/SKILL.md', skillDirectory), 'utf8');
    const design = readFileSync(new URL('expressivecss-design/SKILL.md', skillDirectory), 'utf8');
    const usage = readFileSync(new URL('expressivecss-usage/SKILL.md', skillDirectory), 'utf8');
    const runtime = readFileSync(new URL('expressivecss-runtime/SKILL.md', skillDirectory), 'utf8');
    const theming = readFileSync(new URL('expressivecss-theming/SKILL.md', skillDirectory), 'utf8');
    const accessibility = readFileSync(new URL('expressivecss-accessibility/SKILL.md', skillDirectory), 'utf8');

    assert.match(install, /https:\/\/www\.expressivecss\.com\/index\.html\.md/);
    assert.doesNotMatch(install, /getting-started\.html\.md/);
    assert.match(install, /older.*installed version.*node_modules.*matching repository tag/is);
    assert.match(design, /new surface|refinement|redesign/i);
    assert.match(design, /Material 3 Expressive/);
    assert.match(design, /brand.*tokens/i);
    assert.match(design, /Compact.*Medium.*Expanded.*Large.*Extra-large/s);
    assert.match(design, /loading.*empty.*error.*success/s);
    assert.match(design, /48 by 48 dp/);
    assert.doesNotMatch(design, /44(?:×|x| by )44/);
    assert.match(design, /semantics contract.*authored semantics/i);
    assert.match(design, /Roboto.*Noto.*tokens/s);
    assert.doesNotMatch(design, /density/i);
    assert.match(design, /independent.*review/i);
    assert.match(design, /two.*inspection rounds/i);
    assert.doesNotMatch(design, /imitate|clone|pixel-match/i);
    assert.match(research, /source that owns each question/);
    assert.doesNotMatch(research, /use this order/);
    assert.match(research, /`semantics\.json` governs authored element choice/);
    assert.match(research, /does \*\*not\*\* import.*font prohibitions.*aesthetic bans/s);
    assert.match(changelog, /every reachable state/);
    assert.match(usage, /`\.loading-indicator` for a short indeterminate wait/);
    assert.match(usage, /`\.icon-button` for the Material 3 icon-button component/);
    assert.match(usage, /`\.button\.circle` is the older round common-button form/);
    assert.match(runtime, /Never use `AutoInit\(\)` and `Component\.init\(\)` on the same element/);
    assert.match(runtime, /Add `no-autoinit`/);
    assert.match(runtime, /current\?\.destroy\(\)/);
    assert.match(theming, /live `--md-sys-color-\*` tokens/);
    assert.match(theming, /color-mix\(in oklab/);
    assert.match(accessibility, /48 by 48 dp/);
    assert.match(accessibility, /composite roles/);
    assert.doesNotMatch(accessibility, /presence of state attributes/);
    assert.match(accessibility, /explicitly requires? at author time/);
  });

  test('defines explicit design operating modes and edit boundaries', () => {
    const design = readFileSync(new URL('expressivecss-design/SKILL.md', skillDirectory), 'utf8');
    const modeLine = (mode) => design.match(new RegExp(`^- \\*\\*${mode}\\.\\*\\*.+$`, 'm'))?.[0] ?? '';

    for (const mode of ['Implement', 'Refine', 'Redesign', 'Critique', 'Audit']) {
      assert.ok(modeLine(mode), `${mode} mode is missing`);
    }

    assert.match(modeLine('Implement'), /change code.*render.*test.*evidence/i);
    assert.match(modeLine('Refine'), /preserve.*identity.*content.*information architecture/i);
    assert.match(modeLine('Redesign'), /structural changes.*product requirements/i);
    assert.match(modeLine('Critique'), /visual hierarchy.*without editing/i);
    assert.match(modeLine('Audit'), /measurable.*semantics.*runtime.*responsive.*accessibility.*without editing/i);
    assert.match(design, /Choose one operating mode, or run Critique followed by Audit for a combined review/i);
    assert.match(design, /critique before (?:the )?audit/i);
    assert.match(body, /Before implementing, refining, redesigning, critiquing, or auditing a surface or flow\./);
    assert.match(design, /Implement, Refine, Redesign, or a review where the user separately requested fixes[\s\S]*fix the first evidence batch/i);
    assert.match(design, /In Critique or Audit alone, stop after reporting/i);
  });

  test('uses an evidence-based Material review matrix without a numeric score', () => {
    const design = readFileSync(new URL('expressivecss-design/SKILL.md', skillDirectory), 'utf8');
    const matrix = readFileSync(new URL('expressivecss-design/references/review-matrix.md', skillDirectory), 'utf8');

    assert.match(design, /\[review matrix\]\(\.\/references\/review-matrix\.md\)/i);
    assert.match(matrix, /Pass[\s\S]*Intentional adaptation[\s\S]*Fail[\s\S]*Not applicable/);
    assert.match(matrix, /Area \| Criterion \| Status \| Evidence \| Impact \| Location \| Concrete fix/);

    for (const area of [
      'Component choice and anatomy',
      'Emphasis, containment, shape, type, icons, motion, and state layers',
      'Window-class adaptation and navigation',
      'Semantic color roles and themes',
      'Authored semantics and runtime-owned ARIA',
      'Loading, empty, error, permission, and recovery',
      'Keyboard, focus, contrast, reflow, RTL, and reduced motion',
      'Initialization and teardown',
    ]) {
      assert.ok(matrix.includes(area), `missing review area: ${area}`);
    }

    assert.match(matrix, /Do not calculate a numeric or aggregate score/i);
    assert.match(matrix, /Intentional adaptation[\s\S]*documented rationale[\s\S]*preserves/i);
    assert.match(matrix, /Not applicable[\s\S]*reason/i);
  });
});
