import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { transform } from 'esbuild';

const root = new URL('..', import.meta.url);
const sourceUrl = new URL('../docs/src/data/component-decisions.json', import.meta.url);
const generatedUrl = new URL('../skills/expressivecss/references/component-decisions.md', import.meta.url);
const bundledUrl = new URL('../mcp/expressivecss/component-decisions.json', import.meta.url);
const semanticsUrl = new URL('../semantics.json', import.meta.url);
const reviewMatrixUrl = new URL('../skills/expressivecss/expressivecss-design/references/review-matrix.md', import.meta.url);

const data = JSON.parse(await readFile(sourceUrl, 'utf8'));
const bundled = JSON.parse(await readFile(bundledUrl, 'utf8'));
const semantics = JSON.parse(await readFile(semanticsUrl, 'utf8'));
const generated = await readFile(generatedUrl, 'utf8');
const reviewMatrix = await readFile(reviewMatrixUrl, 'utf8');
const generator = await readFile(new URL('../scripts/gen-expressivecss-skill.mjs', import.meta.url), 'utf8');
const navSource = await readFile(new URL('../docs/src/data/nav.ts', import.meta.url), 'utf8');
const { code: navCode } = await transform(navSource, { format: 'esm', loader: 'ts', target: 'es2020' });
const { NAV } = await import(`data:text/javascript;base64,${Buffer.from(navCode).toString('base64')}`);
const cataloguePageIds = NAV
  .filter((group) => ['Structure', 'Components', 'Forms'].includes(group.label))
  .flatMap((group) => group.pages.map((page) => page.id));
const guideNames = (await readdir(new URL('../skills/expressivecss/components/', import.meta.url)))
  .filter((name) => name.endsWith('.md'))
  .map((name) => name.replace(/\.md$/u, ''))
  .sort();

describe('ExpressiveCSS component decisions', () => {
  test('cover every generated guide exactly once with usable fields', async () => {
    assert.equal(data.schemaVersion, 1);
    assert.equal(data.frameworkVersion, '0.8.0');
    assert.doesNotMatch(generator, /const COMPONENTS\s*=/, 'generator contains a second component catalogue');
    assert.deepEqual(data.components.map((item) => item.slug).sort(), guideNames);
    assert.deepEqual(data.components.map((item) => item.guideSource.pageId), cataloguePageIds);
    assert.equal(new Set(data.components.map((item) => item.slug)).size, guideNames.length);
    for (const component of data.components) {
      assert.ok(component.title);
      assert.ok(Array.isArray(component.aliases), `${component.slug} has no aliases`);
      assert.equal(component.selectable, true, `${component.slug} must be selectable or explicitly excluded`);
      assert.equal(component.excludeReason, null);
      assert.ok(component.guideSource.pageId);
      assert.ok(component.guideSource.heading);
      assert.ok([2, 3].includes(component.guideSource.headingLevel));
      assert.ok(component.guideSource.semantics.length, `${component.slug} has no semantics sources`);
      assert.ok(component.jobs.length, `${component.slug} has no jobs`);
      assert.ok(component.useWhen.length, `${component.slug} has no useWhen`);
      assert.ok(component.avoidWhen.length, `${component.slug} has no avoidWhen`);
      assert.ok(Array.isArray(component.alternatives), `${component.slug} has no alternatives`);
      assert.ok(['css-only', 'auto-init', 'manual', 'native', 'shared-runtime'].includes(component.runtime));
      assert.equal(component.guide, `../components/${component.slug}.md`);
      assert.ok(['material', 'framework-extra'].includes(component.materialGuidance.status));
      if (component.materialGuidance.status === 'material') assert.ok(component.materialGuidance.href);
      const guide = await readFile(new URL(`../skills/expressivecss/components/${component.slug}.md`, import.meta.url), 'utf8');
      assert.match(guide, /^<!-- Generated by scripts\/gen-expressivecss-skill\.mjs\. Do not edit\. -->/);
      assert.ok(guide.includes(`### ${component.title}\n`), `${component.slug} guide title does not match catalogue`);
    }
  });

  test('records common confusions and adaptive substitutions', () => {
    const bySlug = new Map(data.components.map((item) => [item.slug, item]));
    for (const [left, right] of [
      ['dialogs', 'snackbar'],
      ['dialogs', 'banners'],
      ['switches', 'checkboxes'],
      ['navigation-bar', 'navigation-rail'],
      ['navigation-drawer', 'side-sheet'],
      ['bottom-app-bar', 'navigation-bar'],
      ['button-groups', 'segmented-buttons'],
      ['progress', 'loading-indicator'],
      ['app-bar', 'tabs'],
      ['app-bar', 'breadcrumbs'],
      ['button-groups', 'split-button'],
      ['checkboxes', 'segmented-buttons'],
      ['checkboxes', 'chips'],
      ['dialogs', 'floating-sheet'],
      ['lists', 'cards'],
      ['lists', 'carousel'],
      ['lightbox', 'carousel'],
      ['lightbox', 'dialogs'],
      ['tooltips', 'icon-buttons'],
      ['badges', 'chips'],
      ['badges', 'cards'],
      ['drag-handle', 'bottom-sheet'],
      ['date-picker', 'text-fields'],
      ['time-picker', 'text-fields'],
    ]) {
      assert.ok(bySlug.get(left).alternatives.includes(right), `${left} must distinguish ${right}`);
    }
    const slugs = new Set(bySlug.keys());
    for (const component of data.components) {
      assert.equal(new Set(component.alternatives).size, component.alternatives.length);
      for (const alternative of component.alternatives) {
        assert.ok(slugs.has(alternative), `${component.slug} references unknown alternative ${alternative}`);
        assert.notEqual(alternative, component.slug);
      }
      for (const adaptation of component.adaptive) {
        assert.ok(['compact', 'medium', 'expanded', 'large', 'extra-large'].includes(adaptation.window));
        assert.ok(['window', 'container'].includes(adaptation.basis));
        assert.ok(['variant', 'replace-with', 'avoid'].includes(adaptation.kind));
        if (adaptation.component) assert.ok(slugs.has(adaptation.component));
      }
    }
    assert.ok(bySlug.get('navigation-bar').adaptive.some((item) => item.window === 'expanded' && item.component === 'navigation-rail'));
    assert.ok(bySlug.get('bottom-sheet').adaptive.some((item) => item.window === 'expanded' && item.component === 'side-sheet'));
    assert.ok(bySlug.get('fab').adaptive.some((item) => item.window === 'expanded' && item.kind === 'variant'));
    assert.ok(bySlug.get('panes').adaptive.some((item) => item.basis === 'container'));
    assert.ok(bySlug.get('navigation-bar').aliases.includes('bottom navigation'));
    assert.ok(bySlug.get('autocomplete').aliases.includes('typeahead'));
    assert.ok(bySlug.get('dialogs').aliases.includes('modal'));
  });

  test('keeps generated skill and MCP decision data synchronized', () => {
    assert.match(generated, /^<!-- Generated by scripts\/gen-expressivecss-skill\.mjs\. Do not edit\. -->/);
    assert.match(generated, /\| Component \| Use when \| Avoid when \| Alternatives \| Adaptive \| Runtime \|/);
    assert.doesNotMatch(generated, /```|## Contract|## Syntax|## Rules/);
    assert.ok(generated.split('\n').length < 100, 'decision index is not compact');
    for (const component of data.components) {
      assert.ok(generated.includes(`| [${component.title}](${component.guide}) |`));
    }
    assert.equal(bundled.generatedBy, 'mcp/expressivecss/scripts/sync-guides.mjs');
    const { generatedBy, ...bundledCatalogue } = bundled;
    assert.ok(generatedBy);
    assert.deepEqual(bundledCatalogue, data);
  });

  test('keeps each Critique criterion to one falsifiable observation', () => {
    const critique = reviewMatrix.slice(
      reviewMatrix.indexOf('## Critique matrix'),
      reviewMatrix.indexOf('## Audit matrix'),
    );
    const rows = critique.split('\n')
      .filter((line) => /^\| C-[A-Z0-9-]+ \|/u.test(line))
      .map((line) => line.split('|').slice(1, -1).map((cell) => cell.trim()));
    const byId = new Map(rows.map((row) => [row[0], row]));

    assert.equal(byId.size, rows.length, 'Critique criterion IDs must be unique');
    for (const id of [
      'C-TYPE-ROLE',
      'C-TYPE-TOKEN-CONSISTENCY',
      'C-MOTION-PURPOSE',
      'C-MOTION-REDUCED-OUTCOME',
      'C-STATE-LAYER-HOVER',
      'C-STATE-LAYER-FOCUS-VISIBLE',
      'C-STATE-LAYER-PRESSED',
      'C-STATE-LAYER-SELECTED',
      'C-STATE-LAYER-DISABLED',
      'C-LONG-CONTENT-FIT',
      'C-LOCALIZED-CONTENT-FIT',
      'C-CONTENT-ACTIONS-VISIBLE',
      'C-CONTENT-NO-OVERLAP',
      'C-CONTENT-VIEWPORT-OVERFLOW',
      'C-LOCALIZED-READING-ORDER',
    ]) assert.ok(byId.has(id), `missing atomic Critique criterion ${id}`);

    assert.match(byId.get('C-TYPE-ROLE')[3], /uses the declared Material type role/i);
    assert.doesNotMatch(byId.get('C-TYPE-ROLE')[3], /peer|same token/i);
    assert.match(byId.get('C-TYPE-TOKEN-CONSISTENCY')[3], /peer.*same role.*same type token values/i);
    assert.doesNotMatch(byId.get('C-TYPE-TOKEN-CONSISTENCY')[3], /uses the declared Material type role/i);
    assert.match(byId.get('C-MOTION-PURPOSE')[3], /names (?:feedback, state, or spatial continuity|one documented purpose)/i);
    assert.doesNotMatch(byId.get('C-MOTION-PURPOSE')[3], /reduced motion/i);
    assert.match(byId.get('C-MOTION-REDUCED-OUTCOME')[3], /reduced motion.*same task outcome/i);
    assert.doesNotMatch(byId.get('C-MOTION-REDUCED-OUTCOME')[3], /names .*purpose/i);

    const stateIds = [
      ['C-STATE-LAYER-HOVER', 'hover'],
      ['C-STATE-LAYER-FOCUS-VISIBLE', 'focus-visible'],
      ['C-STATE-LAYER-PRESSED', 'pressed'],
      ['C-STATE-LAYER-SELECTED', 'selected'],
      ['C-STATE-LAYER-DISABLED', 'disabled'],
    ];
    for (const [id, state] of stateIds) {
      const claim = byId.get(id)[3];
      assert.match(claim, new RegExp(`\\b${state}\\b`, 'i'));
      for (const [, otherState] of stateIds) {
        if (otherState !== state) assert.doesNotMatch(claim, new RegExp(`\\b${otherState}\\b`, 'i'));
      }
    }

    assert.match(byId.get('C-LONG-CONTENT-FIT')[3], /text.*clipp/i);
    assert.match(byId.get('C-LOCALIZED-CONTENT-FIT')[3], /text.*clipp/i);
    assert.match(byId.get('C-CONTENT-ACTIONS-VISIBLE')[3], /required action.*visible/i);
    assert.match(byId.get('C-CONTENT-NO-OVERLAP')[3], /zero unintended overlap/i);
    assert.match(byId.get('C-CONTENT-VIEWPORT-OVERFLOW')[3], /scrollWidth.*clientWidth/i);
    assert.match(byId.get('C-LOCALIZED-READING-ORDER')[3], /reading order/i);
    for (const id of ['C-LONG-CONTENT-FIT', 'C-LOCALIZED-CONTENT-FIT']) {
      assert.doesNotMatch(byId.get(id)[3], /hidden action|overlap|overflow|reading-order/i);
    }
  });

  test('preserves unique semantics rule IDs in every generated component guide', async () => {
    const allSemanticsRuleIds = Object.values(semantics.rows)
      .flatMap((row) => row.rules.map((rule) => rule.id));
    assert.equal(
      new Set(allSemanticsRuleIds).size,
      allSemanticsRuleIds.length,
      'semantics.json rule IDs must be globally unique and stable',
    );

    for (const component of data.components) {
      const excluded = component.guideSource.excludeRules ?? [];
      assert.equal(new Set(excluded).size, excluded.length, `${component.slug} repeats an excluded rule ID`);
      const selectedRules = component.guideSource.semantics.flatMap((rowId) => {
        assert.ok(semantics.rows[rowId], `${component.slug} names unknown semantics row ${rowId}`);
        return semantics.rows[rowId].rules;
      });
      const selectedIds = new Set(selectedRules.map((rule) => rule.id));
      for (const excludedId of excluded) {
        assert.ok(selectedIds.has(excludedId), `${component.slug} excludes unknown rule ${excludedId}`);
      }
      const expectedIds = selectedRules
        .filter((rule) => !excluded.includes(rule.id))
        .map((rule) => rule.id);
      assert.equal(new Set(expectedIds).size, expectedIds.length, `${component.slug} has duplicate applicable rule IDs`);

      const guide = await readFile(new URL(`../skills/expressivecss/components/${component.slug}.md`, import.meta.url), 'utf8');
      assert.ok(
        guide.includes(`Component ID: \`${component.slug}\``),
        `${component.slug} guide has no stable component ID`,
      );
      const actualIds = [...guide.matchAll(/^- `([a-z0-9-]+)`: /gmu)].map((match) => match[1]);
      assert.equal(new Set(actualIds).size, actualIds.length, `${component.slug} guide repeats a rule ID`);
      assert.deepEqual(actualIds, expectedIds, `${component.slug} guide rule IDs drifted from semantics.json`);
    }

    const componentReview = reviewMatrix.slice(reviewMatrix.indexOf('## Component review groups'));
    assert.match(componentReview, /`buttons@icon-only-control-is-named`/);
    assert.match(componentReview, /\| `buttons` \| `icon-only-control-is-named` \|/);
  });
});
