import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync } from 'node:fs';

const skillUrl = new URL('../skills/expressivecss/SKILL.md', import.meta.url);
const skillDirectory = new URL('../skills/expressivecss/', import.meta.url);
const componentsDirectory = new URL('./components/', skillDirectory);
const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const skill = readFileSync(skillUrl, 'utf8');
const bodyStart = skill.indexOf('\n---\n', 4);
const frontmatter = skill.slice(4, bodyStart);
const body = skill.slice(bodyStart + 5);

const supportGuides = [
  'expressivecss-install/SKILL.md',
  'expressivecss-usage/SKILL.md',
  'expressivecss-theming/SKILL.md',
  'expressivecss-runtime/SKILL.md',
  'expressivecss-accessibility/SKILL.md',
];

const componentEntries = [...body.matchAll(/- \[([^\]]+)\]\(\.\/components\/([a-z-]+\.md)\)/g)]
  .map((match) => ({ label: match[1], name: match[2] }));
const componentLinks = componentEntries.map(({ name }) => name);
const componentFiles = readdirSync(componentsDirectory)
  .filter((name) => name.endsWith('.md'))
  .sort();
const retiredClasses = new Set([
  'btn',
  'modal',
  'nav-wrapper',
  'brand-logo',
  'card-content',
  'lever',
  'filled-in',
  'materialize-textarea',
  'input-field',
]);

describe('the ExpressiveCSS agent skill', () => {
  test('is a portable root skill with a concise discovery trigger', () => {
    assert.ok(skill.startsWith('---\n'));
    assert.ok(bodyStart > 4, 'frontmatter is not closed');
    assert.match(frontmatter, /^name: expressivecss$/m);
    assert.match(frontmatter, /^  author: BaezFJ$/m);
    assert.match(frontmatter, /^  version: "0\.2\.0"$/m);

    const description = frontmatter.match(/^description: (.+)$/m)?.[1];
    assert.ok(description, 'description is missing');
    assert.ok(description.length <= 60, `description is ${description.length} characters`);
    assert.ok(description.endsWith('.'), 'description is not a sentence');
    assert.doesNotMatch(skill, /\/home\/|[A-Z]:\\Users\\/, 'skill contains a machine-local path');
    assert.doesNotMatch(skill, /\]\(\.\.\//, 'root skill links outside the portable skill directory');
  });

  test('routes each task to a focused guide with valid frontmatter', () => {
    for (const path of supportGuides) {
      assert.ok(body.includes(`](${`./${path}`})`), `${path} is not linked from the root skill`);
      const url = new URL(path, skillDirectory);
      assert.ok(existsSync(url), `${path} does not exist`);
      const guide = readFileSync(url, 'utf8');
      assert.ok(guide.startsWith('---\n'), `${path} has no frontmatter`);
      assert.match(guide, new RegExp(`^name: ${path.split('/')[0]}$`, 'm'));
      const description = guide.match(/^description: (.+)$/m)?.[1];
      assert.ok(description, `${path} has no description`);
      assert.ok(description.length <= 60, `${path} description is too long`);
      assert.ok(description.endsWith('.'), `${path} description is not a sentence`);
      assert.doesNotMatch(guide, /\/home\/|[A-Z]:\\Users\\/, `${path} contains a machine-local path`);
      assert.doesNotMatch(guide, /\]\(\.\.\/\.\.\//, `${path} links outside the portable skill directory`);
    }
  });

  test('lists every generated component guide exactly once', () => {
    assert.equal(componentFiles.length, 46);
    assert.deepEqual([...componentLinks].sort(), componentFiles);
    assert.equal(new Set(componentLinks).size, componentLinks.length, 'a component guide is listed more than once');

    for (const name of componentFiles) {
      const guideUrl = new URL(name, componentsDirectory);
      const guide = readFileSync(guideUrl, 'utf8');
      assert.match(guide, /^<!-- Generated by scripts\/gen-expressivecss-skill\.mjs\. Do not edit\. -->/);
      const title = guide.match(/^### (.+)$/m)?.[1];
      assert.equal(title, componentEntries.find((entry) => entry.name === name)?.label);
      assert.match(guide, /\[Component documentation\]\(https:\/\/www\.expressivecss\.com\/.+\.html\.md\)/);
      const sourcePath = guide.match(
        /\[Repository source\]\(https:\/\/github\.com\/BaezFJ\/ExpressiveCSS\/blob\/master\/(docs\/src\/pages\/.+\.astro)\)/,
      )?.[1];
      assert.ok(sourcePath, `${name} has no portable repository source link`);
      assert.ok(existsSync(new URL(`../${sourcePath}`, import.meta.url)), `${name} source link is broken`);
      assert.match(guide, /#### Contract/);
      assert.match(guide, /#### Syntax\n\n```(?:html|js)/);
      assert.match(guide, /#### Rules/);
      const syntax = guide.match(/#### Syntax\n\n```(?:html|js)\n([\s\S]+?)\n```/)?.[1];
      assert.ok(syntax, `${name} has no complete syntax example`);
      const syntaxClasses = [...syntax.matchAll(/class=["']([^"']+)["']/g)]
        .flatMap((match) => match[1].split(/\s+/));
      assert.deepEqual(
        syntaxClasses.filter((className) => retiredClasses.has(className)),
        [],
        `${name} must not teach retired Materialize classes`,
      );
      assert.doesNotMatch(guide, /\]\(\.\.\/\.\.\//, `${name} links outside the portable skill directory`);
      assert.doesNotMatch(guide, /\]\(#[^)]+\)/, `${name} contains a fragment from its source document`);
      assert.doesNotMatch(guide, /\/home\/|[A-Z]:\\Users\\/, `${name} contains a machine-local path`);
    }
  });

  test('keeps generated contracts focused on the selected component', () => {
    const guide = (name) => readFileSync(new URL(name, componentsDirectory), 'utf8');
    assert.match(guide('snackbar.md'), /#### Syntax\n\n```js\nnew Expressive\.Snackbar/);
    assert.doesNotMatch(guide('buttons.md'), /The FAB's actions|aria-expanded/);
    assert.doesNotMatch(guide('date-picker.md'), /A <dialog> takes no name/);
    assert.doesNotMatch(guide('time-picker.md'), /A <dialog> takes no name/);
    assert.doesNotMatch(guide('chips.md'), /^\| Type \|/m);
    assert.doesNotMatch(guide('progress.md'), /\]\(#loading-indicator\)/);
  });

  test('keeps generated component guides synchronized with their sources', () => {
    assert.equal(packageJson.scripts['build:skill'], 'node scripts/gen-expressivecss-skill.mjs');
    const result = spawnSync(process.execPath, ['scripts/gen-expressivecss-skill.mjs', '--check'], {
      cwd: new URL('..', import.meta.url),
      encoding: 'utf8',
    });
    assert.equal(result.status, 0, `${result.stdout}${result.stderr}`);
    assert.match(result.stdout, /46 ExpressiveCSS component guides are current\./);
  });

  test('states the source hierarchy in precedence order', () => {
    for (const url of [
      'https://www.expressivecss.com/m3-guidelines.md',
      'https://www.expressivecss.com/llm.md',
      'https://github.com/BaezFJ/ExpressiveCSS/blob/master/semantics.json',
      'https://www.expressivecss.com/SEMANTICS.md',
      'https://github.com/BaezFJ/ExpressiveCSS/blob/master/docs/agents/expressivecss-skill-research.md',
    ]) {
      assert.ok(skill.includes(`](${url})`), `${url} is not linked`);
    }

    const design = body.indexOf('**Design intent:**');
    const shipped = body.indexOf('**Shipped contract:**');
    const semantics = body.indexOf('**Authored semantics:**');
    const runtime = body.indexOf('**Runtime truth:**');
    assert.ok(design < shipped && shipped < semantics && semantics < runtime,
      'source precedence is not stated in order');
  });

  test('keeps the load-bearing usage, runtime, theme, and accessibility rules', () => {
    const install = readFileSync(new URL('expressivecss-install/SKILL.md', skillDirectory), 'utf8');
    const usage = readFileSync(new URL('expressivecss-usage/SKILL.md', skillDirectory), 'utf8');
    const runtime = readFileSync(new URL('expressivecss-runtime/SKILL.md', skillDirectory), 'utf8');
    const theming = readFileSync(new URL('expressivecss-theming/SKILL.md', skillDirectory), 'utf8');
    const accessibility = readFileSync(new URL('expressivecss-accessibility/SKILL.md', skillDirectory), 'utf8');

    assert.match(install, /https:\/\/www\.expressivecss\.com\/index\.html\.md/);
    assert.doesNotMatch(install, /getting-started\.html\.md/);
    assert.match(usage, /`\.loading-indicator` for a short indeterminate wait/);
    assert.match(usage, /`\.icon-button` for the Material 3 icon-button component/);
    assert.match(usage, /`\.button\.circle` is the older round common-button form/);
    assert.match(runtime, /Never use `AutoInit\(\)` and `Component\.init\(\)` on the same element/);
    assert.match(runtime, /Add `no-autoinit`/);
    assert.match(runtime, /current\?\.destroy\(\)/);
    assert.match(theming, /live `--md-sys-color-\*` tokens/);
    assert.match(theming, /color-mix\(in oklab/);
    assert.match(accessibility, /48 by 48 dp/);
    assert.match(accessibility, /composite roles/);
  });
});