import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { transform } from 'esbuild';

const root = new URL('..', import.meta.url);
const sourceUrl = new URL('../docs/src/data/component-decisions.json', import.meta.url);
const generatedUrl = new URL('../skills/expressivecss/references/component-decisions.md', import.meta.url);
const bundledUrl = new URL('../mcp/expressivecss/component-decisions.json', import.meta.url);
const semanticsUrl = new URL('../semantics.json', import.meta.url);
const reviewMatrixUrl = new URL('../skills/expressivecss/expressivecss-design/references/review-matrix.md', import.meta.url);

const data = JSON.parse(await readFile(sourceUrl, 'utf8'));
const bundled = JSON.parse(await readFile(bundledUrl, 'utf8'));
const semantics = JSON.parse(await readFile(semanticsUrl, 'utf8'));
const generated = await readFile(generatedUrl, 'utf8');
const reviewMatrix = await readFile(reviewMatrixUrl, 'utf8');
const generator = await readFile(new URL('../scripts/gen-expressivecss-skill.mjs', import.meta.url), 'utf8');
const navSource = await readFile(new URL('../docs/src/data/nav.ts', import.meta.url), 'utf8');
const { code: navCode } = await transform(navSource, { format: 'esm', loader: 'ts', target: 'es2020' });
const { NAV } = await import(`data:text/javascript;base64,${Buffer.from(navCode).toString('base64')}`);
const cataloguePageIds = NAV
  .filter((group) => ['Structure', 'Components', 'Forms'].includes(group.label))
  .flatMap((group) => group.pages.map((page) => page.id));
const guideNames = (await readdir(new URL('../skills/expressivecss/components/', import.meta.url)))
  .filter((name) => name.endsWith('.md'))
  .map((name) => name.replace(/\.md$/u, ''))
  .sort();
const bySlug = new Map(data.components.map((item) => [item.slug, item]));

describe('ExpressiveCSS component decisions', () => {
  test('cover every generated guide exactly once with usable fields', async () => {
    assert.equal(data.schemaVersion, 1);
    assert.equal(data.frameworkVersion, JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8')).version);
    assert.doesNotMatch(generator, /const COMPONENTS\s*=/, 'generator contains a second component catalogue');
    assert.deepEqual(data.components.map((item) => item.slug).sort(), guideNames);
    assert.deepEqual(data.components.map((item) => item.guideSource.pageId), cataloguePageIds);
    assert.equal(new Set(data.components.map((item) => item.slug)).size, guideNames.length);
    for (const component of data.components) {
      assert.ok(component.title);
      assert.ok(Array.isArray(component.aliases), `${component.slug} has no aliases`);
      assert.equal(typeof component.selectable, 'boolean');
      if (component.selectable) assert.equal(component.excludeReason, null);
      else assert.ok(component.excludeReason && component.alternatives.length, `${component.slug} needs a reason and replacement`);
      assert.ok(component.guideSource.pageId);
      assert.ok(component.guideSource.heading);
      assert.ok([2, 3].includes(component.guideSource.headingLevel));
      assert.ok(component.guideSource.semantics.length, `${component.slug} has no semantics sources`);
      assert.ok(component.jobs.length, `${component.slug} has no jobs`);
      assert.ok(component.useWhen.length, `${component.slug} has no useWhen`);
      assert.ok(component.avoidWhen.length, `${component.slug} has no avoidWhen`);
      assert.ok(Array.isArray(component.alternatives), `${component.slug} has no alternatives`);
      assert.ok(['css-only', 'auto-init', 'manual', 'native', 'shared-runtime'].includes(component.runtime));
      assert.equal(component.guide, `../components/${component.slug}.md`);
      assert.ok(['material', 'framework-extra'].includes(component.materialGuidance.status));
      if (component.materialGuidance.status === 'material') assert.ok(component.materialGuidance.href);
      const guide = await readFile(new URL(`../skills/expressivecss/components/${component.slug}.md`, import.meta.url), 'utf8');
      assert.match(guide, /^<!-- Generated by scripts\/gen-expressivecss-skill\.mjs\. Do not edit\. -->/);
      assert.ok(guide.includes(`### ${component.title}\n`), `${component.slug} guide title does not match catalogue`);
    }
  });

  test('records common confusions and adaptive substitutions', () => {

    for (const [left, right] of [
      ['dialogs', 'snackbar'],
      ['dialogs', 'banners'],
      ['switches', 'checkboxes'],
      ['navigation-bar', 'navigation-rail'],
      ['navigation-drawer', 'side-sheet'],
      ['bottom-app-bar', 'navigation-bar'],
      ['button-groups', 'radio-buttons'],
      ['progress', 'loading-indicator'],
      ['app-bar', 'tabs'],
      ['app-bar', 'breadcrumbs'],
      ['button-groups', 'split-button'],
      ['checkboxes', 'button-groups'],
      ['checkboxes', 'chips'],
      ['dialogs', 'floating-sheet'],
      ['lists', 'cards'],
      ['lists', 'carousel'],
      ['lightbox', 'carousel'],
      ['lightbox', 'dialogs'],
      ['tooltips', 'icon-buttons'],
      ['badges', 'chips'],
      ['badges', 'cards'],
      ['drag-handle', 'bottom-sheet'],
      ['date-picker', 'text-fields'],
      ['time-picker', 'text-fields'],
    ]) {
      assert.ok(bySlug.get(left).alternatives.includes(right), `${left} must distinguish ${right}`);
    }
    const slugs = new Set(bySlug.keys());
    for (const component of data.components) {
      assert.equal(new Set(component.alternatives).size, component.alternatives.length);
      for (const alternative of component.alternatives) {
        assert.ok(slugs.has(alternative), `${component.slug} references unknown alternative ${alternative}`);
        assert.notEqual(alternative, component.slug);
      }
      for (const adaptation of component.adaptive) {
        assert.ok(['compact', 'medium', 'expanded', 'large', 'extra-large'].includes(adaptation.window));
        assert.ok(['window', 'container'].includes(adaptation.basis));
        assert.ok(['variant', 'replace-with', 'avoid'].includes(adaptation.kind));
        if (adaptation.component) assert.ok(slugs.has(adaptation.component));
      }
    }
    assert.ok(bySlug.get('navigation-bar').adaptive.some((item) => item.window === 'expanded' && item.component === 'navigation-rail'));
    assert.ok(bySlug.get('bottom-sheet').adaptive.some((item) => item.window === 'expanded' && item.component === 'side-sheet'));
    assert.ok(bySlug.get('fab').adaptive.some((item) => item.window === 'expanded' && item.kind === 'variant'));
    assert.ok(bySlug.get('panes').adaptive.some((item) => item.basis === 'container'));
    assert.ok(bySlug.get('navigation-bar').aliases.includes('bottom navigation'));
    assert.ok(bySlug.get('autocomplete').aliases.includes('typeahead'));
    assert.ok(bySlug.get('dialogs').aliases.includes('modal'));
  });

  test('replaces generic warnings with concrete selection examples in the guides', async () => {
    const exampleSlugs = [
      'app-bar', 'panes', 'footer', 'breadcrumbs', 'pagination', 'scrollspy',
      'buttons', 'icon-buttons', 'split-button', 'cards', 'lists', 'floating-sheet',
      'badges', 'carousel', 'lightbox', 'toolbars', 'fieldsets', 'slider', 'chips',
      'date-picker', 'time-picker', 'tabs', 'navigation-bar', 'segmented-buttons',
      'button-groups', 'snackbar', 'banners', 'dialogs', 'progress', 'loading-indicator',
    ];
    for (const component of data.components) {
      assert.doesNotMatch(component.avoidWhen.join(' '), /another component fits|fits the job better/i);
    }
    for (const slug of exampleSlugs) {
      const component = bySlug.get(slug);
      assert.equal(typeof component.selectionExample, 'string', `${slug} needs a wrong-choice example`);
      assert.ok(component.selectionExample.length > 40, `${slug} needs a scenario and reason`);
      const guide = await readFile(new URL(`../skills/expressivecss/components/${slug}.md`, import.meta.url), 'utf8');
      assert.ok(guide.includes(component.selectionExample), `${slug} drops its selection example`);
      assert.ok(!generated.includes(component.selectionExample), `${slug} bloats the decision index`);
    }
    // Protect the distinctions most likely to be lost in further shortening.
    assert.match(bySlug.get('tabs').selectionExample, /navigation.*panels/is);
    assert.match(bySlug.get('button-groups').selectionExample, /submit.*radio/is);
    assert.match(bySlug.get('segmented-buttons').selectionExample, /commands.*radio/is);
    assert.match(bySlug.get('snackbar').selectionExample, /save.*banner.*dialog/is);
    assert.match(bySlug.get('loading-indicator').selectionExample, /determinate.*indeterminate/is);
    assert.match(bySlug.get('progress').selectionExample, /indeterminate linear/i);
  });

  test('keeps upstream evidence distinct from documented support and web extensions', async () => {
    const llm = await readFile(new URL('../llm.md', import.meta.url), 'utf8');
    for (const component of data.components) {
      const mapping = component.materialGuidance;
      assert.ok(['component', 'pattern', 'related', 'none'].includes(mapping.relationship));
      assert.equal(mapping.status, ['component', 'pattern'].includes(mapping.relationship) ? 'material' : 'framework-extra');
      for (const href of [mapping.href, mapping.specHref, mapping.guidelinesHref, mapping.upstreamReview.source, ...(mapping.relatedHrefs ?? [])].filter(Boolean)) {
        const url = new URL(href);
        assert.equal(url.protocol, 'https:');
        assert.ok(['m2.material.io', 'm3.material.io', 'github.com'].includes(url.hostname));
        if (url.hostname === 'github.com') assert.ok(url.pathname.startsWith('/material-components/material-components-android/'));
      }
      assert.ok(mapping.upstreamReview.scope);
      assert.match(mapping.upstreamReview.reviewedOn, /^\d{4}-\d{2}-\d{2}$/);
      const implementation = mapping.implementation;
      assert.match(implementation.reviewedOn, /^\d{4}-\d{2}-\d{2}$/);
      assert.ok(implementation.documentedSupport && implementation.webAdaptation);
      assert.ok(Array.isArray(implementation.limitations));
      assert.ok(llm.includes(`${'#'.repeat(component.guideSource.headingLevel)} ${component.guideSource.heading}\n`));
      assert.ok(implementation.source.startsWith('llm.md#'));
      const guide = await readFile(new URL(`../skills/expressivecss/components/${component.slug}.md`, import.meta.url), 'utf8');
      for (const evidence of [mapping.relationship, mapping.upstreamReview.scope, mapping.upstreamReview.source, implementation.documentedSupport, implementation.webAdaptation, ...implementation.limitations]) {
        assert.ok(guide.includes(evidence), `${component.slug} dropped mapping evidence: ${evidence}`);
      }
    }
    for (const slug of ['fieldsets', 'floating-sheet', 'select', 'autocomplete', 'drag-handle']) assert.equal(bySlug.get(slug).materialGuidance.relationship, 'related');
    for (const slug of ['footer', 'breadcrumbs', 'pagination', 'scrollspy', 'lightbox']) assert.equal(bySlug.get(slug).materialGuidance.relationship, 'none');
    assert.equal(bySlug.get('panes').materialGuidance.relationship, 'pattern');
    assert.equal(new URL(bySlug.get('bottom-app-bar').materialGuidance.href).hostname, 'm2.material.io');
    assert.ok(bySlug.get('date-picker').materialGuidance.implementation.limitations.length);
    assert.ok(bySlug.get('buttons').materialGuidance.implementation.limitations.length);
  });

  test('separates native host semantics from shared runtime ownership', () => {
    for (const slug of ['dialogs', 'bottom-sheet', 'side-sheet', 'floating-sheet']) {
      assert.equal(bySlug.get(slug).runtime, 'shared-runtime', `${slug} must route through shared dialog runtime guidance`);
    }
  });

  test('accounts for the remaining Material and web component reviews without claiming full parity', async () => {
    const prior = new Set(['buttons','navigation-bar','navigation-rail','toolbars','text-fields','dialogs','tooltips']);
    const remaining = data.components.filter(entry => !prior.has(entry.slug));
    assert.equal(remaining.length, 39);
    const names = ['inputs-material-review','layout-material-review','feedback-material-review','web-extensions-review'];
    const references = (await Promise.all(names.map(name => readFile(new URL(`../skills/expressivecss/expressivecss-design/references/${name}.md`, import.meta.url), 'utf8')))).join('\n');
    for (const entry of remaining) {
      const review = entry.materialGuidance.upstreamReview;
      assert.ok(review.requirements && review.sections.length);
      assert.ok(entry.capabilityReview.gaps.length || entry.capabilityReview.browserChecks.length, entry.slug);
      assert.equal(references.split(`](../../components/${entry.slug}.md)`).length - 1, 1, entry.slug);
      for (const source of review.sources) assert.ok(references.includes(source), source);
      if (entry.materialGuidance.relationship === 'none') assert.equal(review.sources.length, 0);
    }
  });

  test('keeps generated skill and MCP decision data synchronized', () => {
    assert.match(generated, /^<!-- Generated by scripts\/gen-expressivecss-skill\.mjs\. Do not edit\. -->/);
    assert.match(generated, /\| Component \| Use when \| Avoid when \| Alternatives \| Runtime \|/);
    assert.doesNotMatch(generated, /```|## Contract|## Syntax|## Rules/);
    assert.ok(generated.split('\n').length < 100, 'decision index is not compact');
    for (const component of data.components) {
      assert.ok(generated.includes(`| [${component.title}](${component.guide}) |`));
    }
    assert.equal(bundled.generatedBy, 'mcp/expressivecss/scripts/sync-guides.mjs');
    const { generatedBy, ...bundledCatalogue } = bundled;
    assert.ok(generatedBy);
    assert.deepEqual(bundledCatalogue, data);
  });

  test('moves complete adaptive guidance into the selected component guide', async () => {
    assert.doesNotMatch(generated, /\| Adaptive \||\| Material guidance \|/);
    for (const component of data.components) {
      const guide = await readFile(new URL(`../skills/expressivecss/components/${component.slug}.md`, import.meta.url), 'utf8');
      assert.ok(guide.includes(`Runtime ownership: \`${component.runtime}\``), `${component.slug} omits runtime ownership`);
      for (const adaptation of component.adaptive) {
        assert.ok(guide.includes(`${adaptation.window} ${adaptation.basis}: ${adaptation.kind}`));
        assert.ok(guide.includes(adaptation.reason));
        if (adaptation.component) assert.ok(guide.includes(`](./${adaptation.component}.md)`));
      }
      if (component.materialGuidance.status === 'material') assert.ok(guide.includes(component.materialGuidance.href));
    }
  });

  test('keeps each Critique criterion to one falsifiable observation', () => {
    const critique = reviewMatrix.slice(
      reviewMatrix.indexOf('## Critique matrix'),
      reviewMatrix.indexOf('## Audit matrix'),
    );
    const rows = critique.split('\n')
      .filter((line) => /^\| C-[A-Z0-9-]+ \|/u.test(line))
      .map((line) => line.split('|').slice(1, -1).map((cell) => cell.trim()));
    const byId = new Map(rows.map((row) => [row[0], row]));

    assert.equal(byId.size, rows.length, 'Critique criterion IDs must be unique');
    for (const id of [
      'C-TYPE-ROLE',
      'C-TYPE-TOKEN-CONSISTENCY',
      'C-MOTION-PURPOSE',
      'C-MOTION-REDUCED-OUTCOME',
      'C-STATE-LAYER-HOVER',
      'C-STATE-LAYER-FOCUS-VISIBLE',
      'C-STATE-LAYER-PRESSED',
      'C-STATE-LAYER-SELECTED',
      'C-STATE-LAYER-DISABLED',
      'C-LONG-CONTENT-FIT',
      'C-LOCALIZED-CONTENT-FIT',
      'C-CONTENT-ACTIONS-VISIBLE',
      'C-CONTENT-NO-OVERLAP',
      'C-CONTENT-VIEWPORT-OVERFLOW',
      'C-LOCALIZED-READING-ORDER',
    ]) assert.ok(byId.has(id), `missing atomic Critique criterion ${id}`);

    assert.match(byId.get('C-TYPE-ROLE')[3], /uses the declared Material type role/i);
    assert.doesNotMatch(byId.get('C-TYPE-ROLE')[3], /peer|same token/i);
    assert.match(byId.get('C-TYPE-TOKEN-CONSISTENCY')[3], /peer.*same role.*same type token values/i);
    assert.doesNotMatch(byId.get('C-TYPE-TOKEN-CONSISTENCY')[3], /uses the declared Material type role/i);
    assert.match(byId.get('C-MOTION-PURPOSE')[3], /names (?:feedback, state, or spatial continuity|one documented purpose)/i);
    assert.doesNotMatch(byId.get('C-MOTION-PURPOSE')[3], /reduced motion/i);
    assert.match(byId.get('C-MOTION-REDUCED-OUTCOME')[3], /reduced motion.*same task outcome/i);
    assert.doesNotMatch(byId.get('C-MOTION-REDUCED-OUTCOME')[3], /names .*purpose/i);

    const stateIds = [
      ['C-STATE-LAYER-HOVER', 'hover'],
      ['C-STATE-LAYER-FOCUS-VISIBLE', 'focus-visible'],
      ['C-STATE-LAYER-PRESSED', 'pressed'],
      ['C-STATE-LAYER-SELECTED', 'selected'],
      ['C-STATE-LAYER-DISABLED', 'disabled'],
    ];
    for (const [id, state] of stateIds) {
      const claim = byId.get(id)[3];
      assert.match(claim, new RegExp(`\\b${state}\\b`, 'i'));
      for (const [, otherState] of stateIds) {
        if (otherState !== state) assert.doesNotMatch(claim, new RegExp(`\\b${otherState}\\b`, 'i'));
      }
    }

    assert.match(byId.get('C-LONG-CONTENT-FIT')[3], /text.*clipp/i);
    assert.match(byId.get('C-LOCALIZED-CONTENT-FIT')[3], /text.*clipp/i);
    assert.match(byId.get('C-CONTENT-ACTIONS-VISIBLE')[3], /required action.*visible/i);
    assert.match(byId.get('C-CONTENT-NO-OVERLAP')[3], /zero unintended overlap/i);
    assert.match(byId.get('C-CONTENT-VIEWPORT-OVERFLOW')[3], /scrollWidth.*clientWidth/i);
    assert.match(byId.get('C-LOCALIZED-READING-ORDER')[3], /reading order/i);
    for (const id of ['C-LONG-CONTENT-FIT', 'C-LOCALIZED-CONTENT-FIT']) {
      assert.doesNotMatch(byId.get(id)[3], /hidden action|overlap|overflow|reading-order/i);
    }
  });

  test('preserves unique semantics rule IDs in every generated component guide', async () => {
    const allSemanticsRuleIds = Object.values(semantics.rows)
      .flatMap((row) => row.rules.map((rule) => rule.id));
    assert.equal(
      new Set(allSemanticsRuleIds).size,
      allSemanticsRuleIds.length,
      'semantics.json rule IDs must be globally unique and stable',
    );

    for (const component of data.components) {
      const excluded = component.guideSource.excludeRules ?? [];
      assert.equal(new Set(excluded).size, excluded.length, `${component.slug} repeats an excluded rule ID`);
      const selectedRules = component.guideSource.semantics.flatMap((rowId) => {
        assert.ok(semantics.rows[rowId], `${component.slug} names unknown semantics row ${rowId}`);
        return semantics.rows[rowId].rules;
      });
      const selectedIds = new Set(selectedRules.map((rule) => rule.id));
      for (const excludedId of excluded) {
        assert.ok(selectedIds.has(excludedId), `${component.slug} excludes unknown rule ${excludedId}`);
      }
      const expectedIds = selectedRules
        .filter((rule) => !excluded.includes(rule.id))
        .map((rule) => rule.id);
      assert.equal(new Set(expectedIds).size, expectedIds.length, `${component.slug} has duplicate applicable rule IDs`);

      const guide = await readFile(new URL(`../skills/expressivecss/components/${component.slug}.md`, import.meta.url), 'utf8');
      assert.ok(
        guide.includes(`Component ID: \`${component.slug}\``),
        `${component.slug} guide has no stable component ID`,
      );
      const actualIds = [...guide.matchAll(/^- `([a-z0-9-]+)`: /gmu)].map((match) => match[1]);
      assert.equal(new Set(actualIds).size, actualIds.length, `${component.slug} guide repeats a rule ID`);
      assert.deepEqual(actualIds, expectedIds, `${component.slug} guide rule IDs drifted from semantics.json`);
    }

    const componentReview = reviewMatrix.slice(reviewMatrix.indexOf('## Component review groups'));
    assert.match(componentReview, /`buttons@icon-only-control-is-named`/);
    assert.match(componentReview, /\| `buttons` \| `icon-only-control-is-named` \|/);
  });
});

// Capability evidence is an operator snapshot, never inferred from test registrations.
describe('Material capability roadmap', () => {
  test('covers the catalogue and foundations without turning constraints into feature gaps', async () => {
    const { buildCapabilityRoadmap } = await import('../scripts/lib/material-capabilities.mjs');
    const { fileURLToPath } = await import('node:url');
    const roadmap = await buildCapabilityRoadmap(data, fileURLToPath(root));
    assert.equal(roadmap.entries.length, data.components.length + 3);
    for (const entry of roadmap.entries) {
      assert.equal(entry.support, entry.sourceReview === 'source-reviewed' ? entry.lastReviewedSupport : 'unassessed');
    }
    assert.deepEqual(roadmap.entries.filter((entry) => entry.kind === 'component' && entry.lastReviewedSupport === 'partial').map((entry) => entry.slug).sort(), data.components.filter(entry => entry.capabilityReview.support === 'partial').map(entry => entry.slug).sort());
    for (const slug of ['bottom-app-bar', 'navigation-drawer', 'icon-buttons', 'segmented-buttons', 'drag-handle']) {
      assert.equal(roadmap.entries.find((entry) => entry.slug === slug).gaps.filter(gap => gap.kind === 'feature').length, 0, slug);
    }
    for (const slug of ['typography', 'shape', 'motion']) assert.equal(roadmap.entries.find((entry) => entry.slug === slug).lastReviewedSupport, 'partial');
    const generatedRoadmap = await readFile(new URL('../skills/expressivecss/references/capability-roadmap.json', import.meta.url), 'utf8');
    assert.deepEqual(JSON.parse(generatedRoadmap), roadmap);
    assert.equal(await readFile(new URL('../mcp/expressivecss/capability-roadmap.json', import.meta.url), 'utf8'), generatedRoadmap);
  });

  test('invalidates changed, missing and added inputs and distinguishes unavailable evidence', async () => {
    const { mkdtemp, mkdir, writeFile, rm } = await import('node:fs/promises');
    const { tmpdir } = await import('node:os');
    const path = await import('node:path');
    const { CAPABILITY_INPUT_DIRECTORIES, buildCapabilityRoadmap, pinDirectory, sha256 } = await import('../scripts/lib/material-capabilities.mjs');
    const temporary = await mkdtemp(path.join(tmpdir(), 'material-capabilities-'));
    try {
      for (const directory of CAPABILITY_INPUT_DIRECTORIES) await mkdir(path.join(temporary, directory), { recursive: true });
      await writeFile(path.join(temporary, 'src/component.ts'), 'original');
      await writeFile(path.join(temporary, 'tests/check.test.js'), 'test');
      const pins = await pinDirectory(temporary, 'src');
      const review = { reviewedOn: '2026-09-07', support: 'partial', sources: pins, inventorySha256: sha256(JSON.stringify(pins)), gaps: [], browserChecks: [{ file: 'tests/check.test.js', name: 'scoped assertion', scope: 'One assertion only' }] };
      const entry = (slug) => ({ slug, title: slug, capabilityReview: structuredClone(review), materialGuidance: { relationship: 'foundation', implementation: { documentedSupport: 'Named scope', webAdaptation: 'Web' }, upstreamReview: { source: 'https://example.com', reviewedOn: '2026-09-07', scope: 'unassessed' } } });
      const fixture = { frameworkVersion: '0.8.0', components: [], foundations: ['typography', 'shape', 'motion'].map(entry) };
      const first = async () => (await buildCapabilityRoadmap(fixture, temporary)).entries[0];
      assert.equal((await first()).browserChecks[0].state, 'not-recorded');
      const directories = [], inputs = [];
      for (const directory of CAPABILITY_INPUT_DIRECTORIES) {
        const directoryPins = await pinDirectory(temporary, directory);
        inputs.push(...directoryPins); directories.push({ path: directory, sha256: sha256(JSON.stringify(directoryPins)) });
      }
      fixture.capabilityBrowserEvidence = { collector: 'scripts/record-capability-evidence.mjs', recordedOn: '2026-09-07', engine: 'chromium', status: 'passed', reportSha256: sha256('report'), directories, inputs, results: [{ file: 'tests/check.test.js', name: 'scoped assertion', status: 'passed' }] };
      assert.equal((await first()).browserEvidence, 'recorded-scoped-pass');
      fixture.capabilityBrowserEvidence.results[0].status = 'failed';
      assert.equal((await first()).browserChecks[0].state, 'recorded-failed');
      fixture.capabilityBrowserEvidence.results[0].status = 'skipped';
      assert.equal((await first()).browserChecks[0].state, 'skipped');
      fixture.capabilityBrowserEvidence.results[0].status = 'passed';
      fixture.capabilityBrowserEvidence.status = 'blocked';
      assert.equal((await first()).browserChecks[0].state, 'blocked');
      fixture.capabilityBrowserEvidence.status = 'passed';
      await writeFile(path.join(temporary, 'tests/new.test.js'), 'new');
      assert.equal((await first()).browserEvidence, 'needs-rerun');
      await rm(path.join(temporary, 'tests/new.test.js'));
      await writeFile(path.join(temporary, 'src/new.ts'), 'new feature');
      assert.equal((await first()).sourceReview, 'needs-review');
      await rm(path.join(temporary, 'src/new.ts'));
      await writeFile(path.join(temporary, 'src/component.ts'), 'changed');
      assert.equal((await first()).support, 'unassessed');
      await rm(path.join(temporary, 'src/component.ts'));
      assert.equal((await first()).sourceReview, 'needs-review');
      fixture.foundations[0].capabilityReview.sources[0].path = '../outside';
      await assert.rejects(first, /Invalid reviewed source pin/);
    } finally { await rm(temporary, { recursive: true, force: true }); }
  });

  test('collects native test events without accepting prose verification claims', async () => {
    const { recordedTestEvent } = await import('../scripts/record-capability-evidence.mjs');
    const event = { type: 'test:pass', data: { file: '/repo/tests/check.test.js', name: 'assertion', details: { duration_ms: 12 } } };
    assert.deepEqual(recordedTestEvent(event, '/repo'), { file: 'tests/check.test.js', name: 'assertion', status: 'passed', durationMs: 12 });
    assert.equal(recordedTestEvent({ type: 'test:stdout', data: { message: 'All tests passed' } }), null);
    assert.equal(recordedTestEvent({ ...event, data: { ...event.data, details: { type: 'suite' } } }), null);
    assert.equal(recordedTestEvent({ ...event, data: { ...event.data, skip: true } }, '/repo').status, 'skipped');
    assert.equal(recordedTestEvent({ ...event, type: 'test:fail' }, '/repo').status, 'failed');
  });
});

describe('Expressive selection and portable capability evidence', () => {
  test('keeps current Expressive replacements first in the selection catalogue', () => {
    const entries = new Map(data.components.map((entry) => [entry.slug, entry]));
    assert.equal(entries.get('bottom-app-bar').alternatives[0], 'toolbars');
    assert.equal(entries.get('navigation-drawer').alternatives[0], 'navigation-rail');
    for (const slug of ['navigation-bar', 'fab']) {
      assert.ok(!entries.get(slug).alternatives.includes('bottom-app-bar'));
    }
    assert.equal(entries.get('segmented-buttons').alternatives[0], 'button-groups');
    assert.deepEqual(data.components.filter((entry) => !entry.selectable).map((entry) => entry.slug).sort(),
      ['bottom-app-bar', 'navigation-drawer', 'segmented-buttons']);
    for (const entry of data.components.filter((item) => item.selectable)) {
      assert.ok(entry.alternatives.every((slug) => entries.get(slug).selectable));
      assert.ok(entry.adaptive.every((item) => !item.component || entries.get(item.component).selectable));
    }
  });

  test('roadmap source links survive packaging and reject invalid revisions and paths', async () => {
    const { buildCapabilityRoadmap, renderCapabilityRoadmap } = await import('../scripts/lib/material-capabilities.mjs');
    const { fileURLToPath } = await import('node:url');
    const { mkdtemp, writeFile, rm } = await import('node:fs/promises');
    const { tmpdir } = await import('node:os');
    const path = await import('node:path');
    const { execFileSync } = await import('node:child_process');
    function validateCapabilityLinks(roadmap, root) {
      assert.match(roadmap.sourceRevision, /^[a-f0-9]{40}$/u, 'Capability links require an immutable source revision');
      const tracked = new Set(execFileSync('git', ['ls-tree', '-r', '--name-only', roadmap.sourceRevision], { cwd: root, encoding: 'utf8' }).trim().split('\n'));
      for (const entry of roadmap.entries) {
        for (const name of [...entry.sources.map((source) => source.path), ...entry.browserChecks.map((check) => check.file)]) {
          assert.ok(!name.split('/').includes('..') && tracked.has(name), `Capability link is absent at the recorded revision: ${name}`);
        }
      }
    }

    const roadmap = await buildCapabilityRoadmap(data, fileURLToPath(root));
    validateCapabilityLinks(roadmap, fileURLToPath(root));
    const directory = await mkdtemp(path.join(tmpdir(), 'expressivecss-portable-roadmap-'));
    try {
      const file = path.join(directory, 'capability-roadmap.md');
      await writeFile(file, renderCapabilityRoadmap(roadmap));
      const markdown = await readFile(file, 'utf8');
      const links = [...markdown.matchAll(/\]\(([^)]+)\)/gu)].map((match) => match[1]);
      assert.ok(links.every((link) => link.startsWith('#') || /^https:\/\//u.test(link)));
      const pinned = links.filter((link) => link.startsWith('https://github.com/BaezFJ/ExpressiveCSS/blob/'));
      assert.equal(pinned.length, roadmap.entries.reduce((count, entry) => count + entry.sources.length + entry.browserChecks.length, 0));
      assert.ok(pinned.every((link) => link.includes(`/blob/${data.sourceRevision}/`)));
      assert.throws(() => renderCapabilityRoadmap({ ...roadmap, sourceRevision: 'master' }), /immutable source revision/u);
      const missing = structuredClone(roadmap);
      missing.entries[0].sources[0].path = 'src/missing-capability-file.ts';
      assert.throws(() => validateCapabilityLinks(missing, fileURLToPath(root)), /absent at the recorded revision/u);
      missing.entries[0].sources[0].path = 'src/../../outside';
      assert.throws(() => renderCapabilityRoadmap(missing), /Invalid capability link path/u);
    } finally {
      await rm(directory, { recursive: true, force: true });
    }
  });
});
